"""Domain 层公开 API。

下游模块（app / infra / api / tests）只从本模块导入；不要绕过本模块直接访问子模块。
"""

from __future__ import annotations

from domain.errors import (
    AuthError,
    DomainError,
    EvidenceServiceError,
    InvalidToken,
    MemoryError,
    OAuthFlowError,
    OwnerMismatch,
    RetrievalError,
    RiskProfileNotReady,
    TaskNotFound,
    ToolExecutionError,
    ToolNotFound,
    UserNotFound,
    WebSearchError,
)
from domain.models import (
    Artifact,
    BaseDomainModel,
    Chunk,
    Citation,
    Corpus,
    EvidenceJudgement,
    EvidenceSpan,
    EvidenceState,
    Fact,
    KbChunk,
    KbDocument,
    KbSourceType,
    Message,
    MessageRole,
    Provider,
    RiskProfile,
    SessionProfile,
    Task,
    TaskMode,
    TaskState,
    ToolCall,
    ToolCallStatus,
    User,
    WebResult,
)
from domain.ports import (
    AuthPort,
    ChatPort,
    EmbedPort,
    EvidencePort,
    KbDocumentRepoPort,
    MemoryPort,
    RetrievePort,
    RiskProfilePort,
    TaskRepoPort,
    UserRepoPort,
    WebSearchPort,
)

__all__ = [
    # errors
    "DomainError",
    "AuthError",
    "InvalidToken",
    "OAuthFlowError",
    "UserNotFound",
    "TaskNotFound",
    "OwnerMismatch",
    "ToolNotFound",
    "ToolExecutionError",
    "RetrievalError",
    "MemoryError",
    "EvidenceServiceError",
    "RiskProfileNotReady",
    "WebSearchError",
    # models
    "BaseDomainModel",
    "User",
    "Task",
    "Message",
    "ToolCall",
    "Artifact",
    "Citation",
    "Chunk",
    "WebResult",
    "EvidenceJudgement",
    "EvidenceSpan",
    "EvidenceState",
    "RiskProfile",
    "KbDocument",
    "KbChunk",
    "KbSourceType",
    "SessionProfile",
    "Fact",
    "Provider",
    "TaskState",
    "TaskMode",
    "MessageRole",
    "ToolCallStatus",
    "Corpus",
    # ports
    "AuthPort",
    "UserRepoPort",
    "TaskRepoPort",
    "EmbedPort",
    "ChatPort",
    "RetrievePort",
    "EvidencePort",
    "RiskProfilePort",
    "KbDocumentRepoPort",
    "WebSearchPort",
    "MemoryPort",
]
