"""Domain 层公开 API。

下游模块（app / infra / api / tests）只从本模块导入；不要绕过本模块直接访问子模块。
"""

from __future__ import annotations

from domain.cases import Case, CaseStatus
from domain.documents import (
    CaseDocument,
    Document,
    DocumentStatus,
    DocumentVersion,
    ProcessingJob,
    ProcessingJobStatus,
    ProcessingStage,
)
from domain.errors import (
    AuthError,
    CaseArchived,
    CaseNotFound,
    DocumentNotFound,
    DomainError,
    EvidenceServiceError,
    InvalidCaseTransition,
    InvalidDocumentTransition,
    InvalidProcessingJobTransition,
    InvalidToken,
    MemoryError,
    OAuthFlowError,
    OwnerMismatch,
    ProcessingJobNotFound,
    RetrievalError,
    RiskProfileNotReady,
    TaskNotFound,
    ToolExecutionError,
    ToolNotFound,
    UserNotFound,
    WebSearchError,
    WorkspaceAccessDenied,
    WorkspaceNotFound,
)
from domain.models import (
    Artifact,
    AuditAction,
    AuditEntry,
    BaseDomainModel,
    Chunk,
    Citation,
    Corpus,
    EvidenceJudgement,
    EvidenceSpan,
    EvidenceState,
    Fact,
    KbChunk,
    KbDocument,
    KbSourceType,
    Message,
    MessageRole,
    Provider,
    RiskProfile,
    SessionProfile,
    Task,
    TaskMode,
    TaskState,
    ToolCall,
    ToolCallStatus,
    User,
    WebResult,
)
from domain.ports import (
    AuditLogPort,
    AuthPort,
    CaseRepoPort,
    ChatPort,
    DocumentLoaderPort,
    EmbedPort,
    EvidencePort,
    KbDocumentRepoPort,
    MemoryPort,
    RetrievePort,
    RiskProfilePort,
    TaskRepoPort,
    UserRepoPort,
    WebSearchPort,
    WorkspaceRepoPort,
)
from domain.workspaces import Workspace, WorkspaceMembership, WorkspaceRole, WorkspaceStatus

__all__ = [
    # errors
    "DomainError",
    "AuthError",
    "InvalidToken",
    "OAuthFlowError",
    "UserNotFound",
    "TaskNotFound",
    "OwnerMismatch",
    "WorkspaceNotFound",
    "WorkspaceAccessDenied",
    "CaseNotFound",
    "CaseArchived",
    "InvalidCaseTransition",
    "DocumentNotFound",
    "ProcessingJobNotFound",
    "InvalidDocumentTransition",
    "InvalidProcessingJobTransition",
    "ToolNotFound",
    "ToolExecutionError",
    "RetrievalError",
    "MemoryError",
    "EvidenceServiceError",
    "RiskProfileNotReady",
    "WebSearchError",
    # models
    "BaseDomainModel",
    "AuditEntry",
    "AuditAction",
    "User",
    "Task",
    "Message",
    "ToolCall",
    "Artifact",
    "Citation",
    "Chunk",
    "WebResult",
    "EvidenceJudgement",
    "EvidenceSpan",
    "EvidenceState",
    "RiskProfile",
    "KbDocument",
    "KbChunk",
    "KbSourceType",
    "SessionProfile",
    "Fact",
    "Provider",
    "TaskState",
    "TaskMode",
    "MessageRole",
    "ToolCallStatus",
    "Corpus",
    "Workspace",
    "WorkspaceMembership",
    "WorkspaceRole",
    "WorkspaceStatus",
    "Case",
    "CaseStatus",
    "Document",
    "DocumentVersion",
    "CaseDocument",
    "ProcessingJob",
    "DocumentStatus",
    "ProcessingJobStatus",
    "ProcessingStage",
    # ports
    "AuthPort",
    "AuditLogPort",
    "UserRepoPort",
    "WorkspaceRepoPort",
    "CaseRepoPort",
    "TaskRepoPort",
    "EmbedPort",
    "ChatPort",
    "RetrievePort",
    "EvidencePort",
    "RiskProfilePort",
    "KbDocumentRepoPort",
    "DocumentLoaderPort",
    "WebSearchPort",
    "MemoryPort",
]
