"""initial core schema

Revision ID: 0ddb370aee40
Revises:
Create Date: 2026-08-17 11:11:26.346993
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "0ddb370aee40"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("workspace_id"),
    )
    op.create_index(op.f("ix_workspaces_status"), "workspaces", ["status"], unique=False)
    op.create_index(op.f("ix_workspaces_updated_at"), "workspaces", ["updated_at"], unique=False)
    op.create_table(
        "compliance_cases",
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("jurisdiction", sa.String(length=32), nullable=False),
        sa.Column("scenario_type", sa.String(length=100), nullable=False),
        sa.Column("assessment_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=256), nullable=False),
        sa.Column("reviewer_id", sa.String(length=256), nullable=True),
        sa.Column("active_assessment_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("case_id"),
    )
    op.create_index(
        "ix_cases_workspace_updated",
        "compliance_cases",
        ["workspace_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_cases_status"), "compliance_cases", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_compliance_cases_workspace_id"), "compliance_cases", ["workspace_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.Column("logical_name", sa.String(length=255), nullable=False),
        sa.Column("document_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("current_version_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_index(
        op.f("ix_documents_document_type"), "documents", ["document_type"], unique=False
    )
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_index(op.f("ix_documents_workspace_id"), "documents", ["workspace_id"], unique=False)
    op.create_index(
        "ix_documents_workspace_updated", "documents", ["workspace_id", "updated_at"], unique=False
    )
    op.create_table(
        "policy_rules",
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column("ruleset_version", sa.String(length=128), nullable=False),
        sa.Column("jurisdiction", sa.String(length=32), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "required_fact_fields",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "condition",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "source_clause_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workspace_id", "rule_id", "ruleset_version"),
    )
    op.create_index(
        "ix_policy_rules_lookup",
        "policy_rules",
        ["workspace_id", "ruleset_version", "jurisdiction", "status", "effective_from"],
        unique=False,
    )
    op.create_index(op.f("ix_policy_rules_status"), "policy_rules", ["status"], unique=False)
    op.create_table(
        "workspace_memberships",
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workspace_id", "user_id"),
    )
    op.create_index(
        op.f("ix_workspace_memberships_user_id"), "workspace_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "agent_runs",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("workflow_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("thread_id", sa.String(length=256), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=128), nullable=True),
        sa.Column("current_stage", sa.String(length=100), nullable=False),
        sa.Column(
            "model_config_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("token_usage", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "revision >= 1",
            name="agent_runs_revision_check",
        ),
        sa.ForeignKeyConstraint(["case_id"], ["compliance_cases.case_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id"),
        sa.UniqueConstraint("thread_id"),
    )
    op.create_index(
        "ix_agent_runs_case_created", "agent_runs", ["case_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_agent_runs_case_id"), "agent_runs", ["case_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_status"), "agent_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_agent_runs_workspace_id"), "agent_runs", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_agent_runs_active_case_workflow",
        "agent_runs",
        ["case_id", "workflow_type"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('queued','running','waiting_for_user','waiting_for_review','retrying')"
        ),
        sqlite_where=sa.text(
            "status IN ('queued','running','waiting_for_user','waiting_for_review','retrying')"
        ),
    )
    op.create_table(
        "assessments",
        sa.Column("assessment_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("assessment_date", sa.Date(), nullable=False),
        sa.Column("jurisdiction", sa.String(length=32), nullable=False),
        sa.Column("ruleset_version", sa.String(length=128), nullable=False),
        sa.Column(
            "fact_versions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "policy_evaluations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("risk_level", sa.String(length=32), nullable=False),
        sa.Column(
            "candidate_paths",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("generated_by_run_id", sa.String(length=128), nullable=True),
        sa.Column("approved_by", sa.String(length=256), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["compliance_cases.case_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("assessment_id"),
        sa.UniqueConstraint("case_id", "version"),
    )
    op.create_index(
        "ix_assessments_case_version", "assessments", ["case_id", "version"], unique=False
    )
    op.create_index(op.f("ix_assessments_status"), "assessments", ["status"], unique=False)
    op.create_table(
        "case_documents",
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("added_by", sa.String(length=256), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["compliance_cases.case_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.document_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("case_id", "document_id"),
    )
    op.create_table(
        "case_facts",
        sa.Column("fact_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("field_name", sa.String(length=128), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("criticality", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("confirmed_by", sa.String(length=256), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["compliance_cases.case_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("fact_id"),
    )
    op.create_index(
        "ix_case_facts_case_updated", "case_facts", ["case_id", "updated_at"], unique=False
    )
    op.create_index(op.f("ix_case_facts_field_name"), "case_facts", ["field_name"], unique=False)
    op.create_index(op.f("ix_case_facts_status"), "case_facts", ["status"], unique=False)
    op.create_table(
        "document_versions",
        sa.Column("version_id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=1000), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("parser_version", sa.String(length=100), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.document_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("version_id"),
        sa.UniqueConstraint("document_id", "version_number"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index(
        "ix_document_versions_document",
        "document_versions",
        ["document_id", "version_number"],
        unique=False,
    )
    op.create_table(
        "assessment_actions",
        sa.Column("action_id", sa.String(length=128), nullable=False),
        sa.Column("assessment_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=256), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "related_finding_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.assessment_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("action_id"),
    )
    op.create_index(
        op.f("ix_assessment_actions_assessment_id"),
        "assessment_actions",
        ["assessment_id"],
        unique=False,
    )
    op.create_table(
        "assessment_evidence_citations",
        sa.Column("citation_id", sa.String(length=128), nullable=False),
        sa.Column("assessment_id", sa.String(length=128), nullable=False),
        sa.Column("source_evidence_id", sa.String(length=128), nullable=False),
        sa.Column("fact_id", sa.String(length=128), nullable=False),
        sa.Column("fact_version", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=128), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.assessment_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("citation_id"),
        sa.UniqueConstraint("assessment_id", "source_evidence_id"),
    )
    op.create_index(
        "ix_assessment_evidence_fact",
        "assessment_evidence_citations",
        ["assessment_id", "fact_id"],
        unique=False,
    )
    op.create_table(
        "assessment_findings",
        sa.Column("finding_id", sa.String(length=128), nullable=False),
        sa.Column("assessment_id", sa.String(length=128), nullable=False),
        sa.Column("finding_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "fact_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "evidence_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "clause_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "rule_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.assessment_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_index(
        op.f("ix_assessment_findings_assessment_id"),
        "assessment_findings",
        ["assessment_id"],
        unique=False,
    )
    op.create_table(
        "case_fact_versions",
        sa.Column("fact_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["fact_id"], ["case_facts.fact_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("fact_id", "version"),
    )
    op.create_table(
        "document_parse_snapshots",
        sa.Column("snapshot_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=128), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.version_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("snapshot_id"),
        sa.UniqueConstraint("document_version_id"),
    )
    op.create_table(
        "evidence_chunks",
        sa.Column("chunk_id", sa.String(length=256), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=128), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "embedding",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["compliance_cases.case_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.document_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.version_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("chunk_id"),
        sa.UniqueConstraint("case_id", "document_version_id", "page_number", "chunk_index"),
    )
    op.create_index(
        op.f("ix_evidence_chunks_case_id"), "evidence_chunks", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_chunks_document_version_id"),
        "evidence_chunks",
        ["document_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_evidence_chunks_scope",
        "evidence_chunks",
        ["workspace_id", "case_id", "document_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_chunks_workspace_id"), "evidence_chunks", ["workspace_id"], unique=False
    )
    op.create_table(
        "processing_jobs",
        sa.Column("job_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_stage", sa.String(length=64), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 1",
            name="processing_jobs_progress_check",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.version_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(op.f("ix_processing_jobs_status"), "processing_jobs", ["status"], unique=False)
    op.create_index(
        "ix_processing_jobs_version_created",
        "processing_jobs",
        ["document_version_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "run_checkpoints",
        sa.Column("checkpoint_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("thread_id", sa.String(length=256), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=100), nullable=False),
        sa.Column(
            "state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("checkpoint_id"),
        sa.UniqueConstraint("run_id", "version"),
    )
    op.create_index(
        "ix_run_checkpoints_run_version", "run_checkpoints", ["run_id", "version"], unique=False
    )
    op.create_table(
        "run_events",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=100), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("run_id", "sequence"),
    )
    op.create_index(
        "ix_run_events_run_sequence", "run_events", ["run_id", "sequence"], unique=False
    )
    op.create_table(
        "case_fact_evidence",
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("fact_id", sa.String(length=128), nullable=False),
        sa.Column("fact_version", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=128), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["compliance_cases.case_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.document_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.version_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["fact_id", "fact_version"],
            ["case_fact_versions.fact_id", "case_fact_versions.version"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("evidence_id"),
    )
    op.create_index(
        op.f("ix_case_fact_evidence_case_id"), "case_fact_evidence", ["case_id"], unique=False
    )
    op.create_index(
        "ix_case_fact_evidence_fact",
        "case_fact_evidence",
        ["fact_id", "fact_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_fact_evidence_fact_id"), "case_fact_evidence", ["fact_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_fact_evidence_fact_id"), table_name="case_fact_evidence")
    op.drop_index("ix_case_fact_evidence_fact", table_name="case_fact_evidence")
    op.drop_index(op.f("ix_case_fact_evidence_case_id"), table_name="case_fact_evidence")
    op.drop_table("case_fact_evidence")
    op.drop_index("ix_run_events_run_sequence", table_name="run_events")
    op.drop_table("run_events")
    op.drop_index("ix_run_checkpoints_run_version", table_name="run_checkpoints")
    op.drop_table("run_checkpoints")
    op.drop_index("ix_processing_jobs_version_created", table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_status"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_evidence_chunks_workspace_id"), table_name="evidence_chunks")
    op.drop_index("ix_evidence_chunks_scope", table_name="evidence_chunks")
    op.drop_index(op.f("ix_evidence_chunks_document_version_id"), table_name="evidence_chunks")
    op.drop_index(op.f("ix_evidence_chunks_case_id"), table_name="evidence_chunks")
    op.drop_table("evidence_chunks")
    op.drop_table("document_parse_snapshots")
    op.drop_table("case_fact_versions")
    op.drop_index(op.f("ix_assessment_findings_assessment_id"), table_name="assessment_findings")
    op.drop_table("assessment_findings")
    op.drop_index("ix_assessment_evidence_fact", table_name="assessment_evidence_citations")
    op.drop_table("assessment_evidence_citations")
    op.drop_index(op.f("ix_assessment_actions_assessment_id"), table_name="assessment_actions")
    op.drop_table("assessment_actions")
    op.drop_index("ix_document_versions_document", table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_case_facts_status"), table_name="case_facts")
    op.drop_index(op.f("ix_case_facts_field_name"), table_name="case_facts")
    op.drop_index("ix_case_facts_case_updated", table_name="case_facts")
    op.drop_table("case_facts")
    op.drop_table("case_documents")
    op.drop_index(op.f("ix_assessments_status"), table_name="assessments")
    op.drop_index("ix_assessments_case_version", table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(
        "uq_agent_runs_active_case_workflow",
        table_name="agent_runs",
        postgresql_where=sa.text(
            "status IN ('queued','running','waiting_for_user','waiting_for_review','retrying')"
        ),
        sqlite_where=sa.text(
            "status IN ('queued','running','waiting_for_user','waiting_for_review','retrying')"
        ),
    )
    op.drop_index(op.f("ix_agent_runs_workspace_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_status"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_case_id"), table_name="agent_runs")
    op.drop_index("ix_agent_runs_case_created", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_workspace_memberships_user_id"), table_name="workspace_memberships")
    op.drop_table("workspace_memberships")
    op.drop_index(op.f("ix_policy_rules_status"), table_name="policy_rules")
    op.drop_index("ix_policy_rules_lookup", table_name="policy_rules")
    op.drop_table("policy_rules")
    op.drop_index("ix_documents_workspace_updated", table_name="documents")
    op.drop_index(op.f("ix_documents_workspace_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_document_type"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_compliance_cases_workspace_id"), table_name="compliance_cases")
    op.drop_index(op.f("ix_compliance_cases_status"), table_name="compliance_cases")
    op.drop_index("ix_cases_workspace_updated", table_name="compliance_cases")
    op.drop_table("compliance_cases")
    op.drop_index(op.f("ix_workspaces_updated_at"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_status"), table_name="workspaces")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
